fix: update workflow to check whether it is using Expo project directory

diff --git a/.github/workflows/expo-preview.yaml b/.github/workflows/expo-preview.yaml
--- a/.github/workflows/expo-preview.yaml
+++ b/.github/workflows/expo-preview.yaml
@@ -31,9 +31,15 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+      - name: Verify Expo project
+        run: |
+          if [ ! -f app.json ]; then
+            echo "Error: app.json not found. Ensure you are in the Expo project directory."
+            exit 1
+          fi
+
       - name: Create preview
-        uses: expo/expo-github-action/preview@v8
-        with:
-          # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
-          # Use your own, or keep the automatically inferred branch name from `--auto`, when using different triggers.
-          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
+        # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
+        # Use your own, or keep the automatically inferred branch name from `--auto`, when using different triggers.
+        run:
+          eas update --auto --branch ${{ github.event.pull_request.head.ref }}
